// src/config/gameConfig.ts

export const DETECTOR_CONFIG = {
  SMOOTHING_WINDOW: 10,
  SCORE_THRESHOLD: 0.4,
  TARGET_FPS: 20,
};

export const PRACTICE_MODE_CONFIG = {
  BASE_HOLD_MS: 800,
  HOLD_MS_INCREMENT: 100,
  BASE_THRESHOLD: 0.55,
  THRESHOLD_INCREMENT: 0.03,
  MAX_THRESHOLD: 0.75,
};

export const GAME_TIMING = {
  ROUND_COUNTDOWN_TICK_MS: 100,
  CLASSIC_ROUND_DURATION_MULTIPLIER: 4,
  TIME_ATTACK_ROUND_DURATION_MULTIPLIER: 3,
  MIRROR_ROUND_DURATION_MULTIPLIER: 4.5,
  CLASSIC_ROUND_MIN_DURATION_MS: 8000,
  TIME_ATTACK_ROUND_MIN_DURATION_MS: 5000,
  MIRROR_ROUND_MIN_DURATION_MS: 10000,
  TIME_ATTACK_STEP_MS: 120,
  MIRROR_STEP_MS: 90,
  CLASSIC_STEP_MS: 100,
  SUCCESS_TO_REWARD_DELAY_MS: 80,
  REWARD_TO_NEXT_ROUND_DELAY_MS: 700,
};

export const GAME_SCORING = {
  PERFECT_THRESHOLD_PROB: 0.9,
  PERFECT_THRESHOLD_ADDITION: 0.2,
  COMBO_MAX: 10,
  XP_BASE: 10,
  XP_STAR_MULTIPLIER: 3,
  XP_STREAK_MULTIPLIER: 2,
  XP_STREAK_MAX_BONUS: 10,
};

export const GAME_DIFFICULTY = {
  DEFAULT_THRESHOLD: 0.6,
  DEFAULT_HOLD_MS: 900,
  MIN_ADAPTIVE_THRESHOLD: 0.5,
  MAX_ADAPTIVE_THRESHOLD: 0.9,
  FAST_PASS_FRAMES: 4,
  FAST_PASS_THRESHOLD_MULTIPLIER: 0.95,
};

export const EFFECT_CONFIG = {
  DEFAULT_PARTICLE_COUNT: 180,
  DEFAULT_COLOR_SATURATION: 0.8,
  DEFAULT_GLOW_STRENGTH: 0.5,
  DEFAULT_SFX_GAIN: 0.12,
  PARTICLE_MIN: 100,
  PARTICLE_MAX: 340,
  CONFETTI_SPEED_MULTIPLIER: 0.7,
  PERFECT_CONFETTI_SPEED: 1.55,
  PERFECT_CONFETTI_PARTICLE_MULTIPLIER: 1.5,
  PERFECT_CONFETTI_PARTICLE_ADDITION: 120,
};

export const STICKER_CONFIG = {
  RANDOM_X_RANGE: 260,
  RANDOM_X_OFFSET: 20,
  RANDOM_Y_RANGE: 120,
  RANDOM_Y_OFFSET: 20,
};

export const SOUND_CONFIG = {
  SUCCESS_CHIME_GAIN: 0.12,
};
